name: Test
on:
  pull_request:
  push:
    branches:
      - main

    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup MoonBit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@develop

      - name: Check Moonbit Version
        run: |
          moon version --all
          moon update
          moon install

      - name: Run tests with coverage
        run: |
          moon test
